SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI
	INNER JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE REGEXP_LIKE(SEX_UPON_INTAKE, 'Intact')
	AND REGEXP_LIKE(SEX_UPON_OUTCOME, 'Spayed|Neutered')
ORDER BY AI.ANIMAL_ID;